export const SUPABASE_URL = "https://jaoxjyhietvuklyggybh.supabase.co";
export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imphb3hqeWhpZXR2dWtseWd5Z2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3Mzc4NTIsImV4cCI6MjA4ODMxMzg1Mn0.b4e0TlWDCmJyaTd_jn4qsaoubCZ3Go_pjv0wduTaOBU";
